[package]
name = "pango"
documentation = "https://e-monkeys-tech/gtk4-rs-core/stable/latest/docs/pango/"
homepage = "https://gtk-rs.org/"
authors = ["The gtk-rs Project Developers"]
keywords = ["pango", "gtk-rs", "gnome"]
readme = "README.md"
version = "0.15.0"
description = "Rust bindings for the Pango library"
repository = "https://github.com/e-monkeys-tech/gtk4-rs-core"
license = "MIT"
exclude = [
    "gir-files/*",
]
edition = "2018"

[features]
v1_40 = []
v1_42 = ["v1_40", "ffi/v1_42"]
v1_44 = ["v1_42", "ffi/v1_44"]
v1_46 = ["v1_44", "ffi/v1_46"]
dox = ["ffi/dox", "glib/dox"]

[package.metadata.docs.rs]
features = ["dox"]

[dependencies]
libc = "0.2"
bitflags = "1.0"
once_cell = "1.0"
ffi = { package = "pango-sys", path = "sys" }
glib = { path = "../glib" }

[dev-dependencies]
gir-format-check = "^0.1"
